"""User profile model (mirrors a Supabase Auth user)."""

import datetime
import uuid

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class User(Base, TimestampMixin):
    """App-side profile. ``id`` equals the Supabase Auth user id (JWT ``sub``)."""

    __tablename__ = "users"

    # No uuid_pk() here — this id is NOT generated by us. It must exactly
    # match the id Supabase Auth already assigned to this user, so there's
    # no separate mapping table needed between "our" user and "their" user.
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)  # = supabase auth.users.id
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Globally unique (matches Supabase Auth's own global-per-project uniqueness),
    # not just unique within one tenant.
    email: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String, nullable=False)  # display name
    role: Mapped[str] = mapped_column(String, nullable=False, default="user")  # admin|user
    avatar_initials: Mapped[str] = mapped_column(String, nullable=False, default="")
    # NULL means this user was invited but has never actually logged in yet —
    # that's how the UI shows "pending invite" without a separate status column.
    last_login_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
