import type {
  Document,
  Tenant,
  User,
  ActivityEvent,
} from "@/types";

export const mockTenant: Tenant = {
  id: "tenant_01",
  name: "Syarikat Maju Sdn Bhd",
  plan: "professional",
  storageUsedBytes: 2_847_293_440,
  storageLimitBytes: 10_737_418_240,
  documentsCount: 1247,
  createdAt: "2025-01-15T08:00:00Z",
};

export const mockCurrentUser: User = {
  id: "user_01",
  email: "admin@majusb.com.my",
  name: "Ahmad Razif",
  role: "admin",
  avatarInitials: "AR",
  tenantId: "tenant_01",
  createdAt: "2025-01-15T08:00:00Z",
  lastLoginAt: "2026-06-04T07:30:00Z",
};

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: "user_02",
    email: "siti.nurhaliza@majusb.com.my",
    name: "Siti Nurhaliza",
    role: "user",
    avatarInitials: "SN",
    tenantId: "tenant_01",
    createdAt: "2025-02-01T09:00:00Z",
    lastLoginAt: "2026-06-03T14:20:00Z",
  },
  {
    id: "user_03",
    email: "lee.wei.ming@majusb.com.my",
    name: "Lee Wei Ming",
    role: "user",
    avatarInitials: "LW",
    tenantId: "tenant_01",
    createdAt: "2025-03-10T10:00:00Z",
    lastLoginAt: "2026-06-04T06:45:00Z",
  },
  {
    id: "user_04",
    email: "raj.kumar@majusb.com.my",
    name: "Raj Kumar",
    role: "user",
    avatarInitials: "RK",
    tenantId: "tenant_01",
    createdAt: "2025-04-20T11:00:00Z",
    lastLoginAt: "2026-06-02T16:10:00Z",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    tenantId: "tenant_01",
    filename: "invoice_TNB_2026_05.pdf",
    originalFilename: "Invoice TNB May 2026.pdf",
    documentType: "invoice",
    mimeType: "application/pdf",
    sizeBytes: 248_320,
    status: "completed",
    uploadedBy: "Ahmad Razif",
    uploadedAt: "2026-06-03T09:15:00Z",
    processedAt: "2026-06-03T09:16:42Z",
    pageCount: 3,
    hasTextLayer: true,
    ocrConfidence: null,
    extractedData: {
      vendor: "Tenaga Nasional Berhad",
      invoiceNumber: "INV-2026-0512345",
      invoiceDate: "2026-05-31",
      dueDate: "2026-06-15",
      totalAmount: 1284.50,
      currency: "MYR",
      accountNumber: "ACCT-78234910",
      lineItems: [
        { description: "Electricity Consumption", quantity: 1, unitPrice: 1180.00, amount: 1180.00 },
        { description: "Service Charge", quantity: 1, unitPrice: 80.00, amount: 80.00 },
        { description: "SST 6%", quantity: 1, unitPrice: 24.50, amount: 24.50 },
      ],
    },
    tags: ["utilities", "may-2026", "tnb"],
    storageKey: "tenant_01/docs/doc_001.pdf",
  },
  {
    id: "doc_002",
    tenantId: "tenant_01",
    filename: "contract_vendor_sdn_bhd_2026.pdf",
    originalFilename: "Vendor Agreement - Logistik Jaya.pdf",
    documentType: "contract",
    mimeType: "application/pdf",
    sizeBytes: 1_024_000,
    status: "completed",
    uploadedBy: "Siti Nurhaliza",
    uploadedAt: "2026-06-03T11:30:00Z",
    processedAt: "2026-06-03T11:34:10Z",
    pageCount: 14,
    hasTextLayer: true,
    ocrConfidence: null,
    extractedData: {
      contractTitle: "Service Agreement",
      partyA: "Syarikat Maju Sdn Bhd",
      partyB: "Logistik Jaya Sdn Bhd",
      startDate: "2026-07-01",
      endDate: "2027-06-30",
      contractValue: 85000.00,
      currency: "MYR",
    },
    tags: ["contract", "vendor", "2026"],
    storageKey: "tenant_01/docs/doc_002.pdf",
  },
  {
    id: "doc_003",
    tenantId: "tenant_01",
    filename: "receipt_parking_0603.jpg",
    originalFilename: "parking receipt 3 june.jpg",
    documentType: "receipt",
    mimeType: "image/jpeg",
    sizeBytes: 512_000,
    status: "completed",
    uploadedBy: "Lee Wei Ming",
    uploadedAt: "2026-06-03T14:05:00Z",
    processedAt: "2026-06-03T14:06:55Z",
    pageCount: 1,
    hasTextLayer: false,
    ocrConfidence: 0.94,
    extractedData: {
      vendor: "Wilson Parking KLCC",
      receiptNumber: "PKG-20260603-18234",
      date: "2026-06-03",
      totalAmount: 12.00,
      currency: "MYR",
      duration: "2.5 hours",
    },
    tags: ["receipt", "parking", "june-2026"],
    storageKey: "tenant_01/docs/doc_003.jpg",
  },
  {
    id: "doc_004",
    tenantId: "tenant_01",
    filename: "report_quarterly_q1_2026.pdf",
    originalFilename: "Q1 2026 Financial Report.pdf",
    documentType: "report",
    mimeType: "application/pdf",
    sizeBytes: 3_145_728,
    status: "ai_extraction",
    uploadedBy: "Ahmad Razif",
    uploadedAt: "2026-06-04T08:00:00Z",
    processedAt: null,
    pageCount: 42,
    hasTextLayer: true,
    ocrConfidence: null,
    extractedData: null,
    tags: ["report", "finance", "q1-2026"],
    storageKey: "tenant_01/docs/doc_004.pdf",
  },
  {
    id: "doc_005",
    tenantId: "tenant_01",
    filename: "invoice_telekom_may26.pdf",
    originalFilename: "Telekom Invoice May 2026.pdf",
    documentType: "invoice",
    mimeType: "application/pdf",
    sizeBytes: 196_608,
    status: "ocr_processing",
    uploadedBy: "Siti Nurhaliza",
    uploadedAt: "2026-06-04T08:45:00Z",
    processedAt: null,
    pageCount: 2,
    hasTextLayer: false,
    ocrConfidence: null,
    extractedData: null,
    tags: ["utilities", "telekom"],
    storageKey: "tenant_01/docs/doc_005.pdf",
  },
  {
    id: "doc_006",
    tenantId: "tenant_01",
    filename: "form_hrdf_levy_q1.pdf",
    originalFilename: "HRDF Levy Form Q1 2026.pdf",
    documentType: "form",
    mimeType: "application/pdf",
    sizeBytes: 384_000,
    status: "extracting_text",
    uploadedBy: "Raj Kumar",
    uploadedAt: "2026-06-04T09:00:00Z",
    processedAt: null,
    pageCount: 4,
    hasTextLayer: true,
    ocrConfidence: null,
    extractedData: null,
    tags: ["hrdf", "levy", "q1-2026"],
    storageKey: "tenant_01/docs/doc_006.pdf",
  },
  {
    id: "doc_007",
    tenantId: "tenant_01",
    filename: "invoice_petronas_fuel.pdf",
    originalFilename: "Petronas Fuel Card Invoice.pdf",
    documentType: "invoice",
    mimeType: "application/pdf",
    sizeBytes: 164_480,
    status: "queued",
    uploadedBy: "Lee Wei Ming",
    uploadedAt: "2026-06-04T09:10:00Z",
    processedAt: null,
    pageCount: null,
    hasTextLayer: false,
    ocrConfidence: null,
    extractedData: null,
    tags: ["fuel", "petronas"],
    storageKey: "tenant_01/docs/doc_007.pdf",
  },
  {
    id: "doc_008",
    tenantId: "tenant_01",
    filename: "letter_lhdn_notice.pdf",
    originalFilename: "LHDN Tax Assessment Notice.pdf",
    documentType: "letter",
    mimeType: "application/pdf",
    sizeBytes: 288_000,
    status: "failed",
    uploadedBy: "Ahmad Razif",
    uploadedAt: "2026-06-02T16:30:00Z",
    processedAt: "2026-06-02T16:31:00Z",
    pageCount: 6,
    hasTextLayer: false,
    ocrConfidence: null,
    extractedData: null,
    tags: ["lhdn", "tax"],
    storageKey: "tenant_01/docs/doc_008.pdf",
  },
];

export const mockActivity: ActivityEvent[] = [
  {
    id: "evt_01",
    type: "upload",
    documentId: "doc_007",
    documentName: "Petronas Fuel Card Invoice.pdf",
    userId: "user_03",
    userName: "Lee Wei Ming",
    timestamp: "2026-06-04T09:10:00Z",
  },
  {
    id: "evt_02",
    type: "upload",
    documentId: "doc_006",
    documentName: "HRDF Levy Form Q1 2026.pdf",
    userId: "user_04",
    userName: "Raj Kumar",
    timestamp: "2026-06-04T09:00:00Z",
  },
  {
    id: "evt_03",
    type: "upload",
    documentId: "doc_005",
    documentName: "Telekom Invoice May 2026.pdf",
    userId: "user_02",
    userName: "Siti Nurhaliza",
    timestamp: "2026-06-04T08:45:00Z",
  },
  {
    id: "evt_04",
    type: "upload",
    documentId: "doc_004",
    documentName: "Q1 2026 Financial Report.pdf",
    userId: "user_01",
    userName: "Ahmad Razif",
    timestamp: "2026-06-04T08:00:00Z",
  },
  {
    id: "evt_05",
    type: "processing_complete",
    documentId: "doc_003",
    documentName: "parking receipt 3 june.jpg",
    userId: "user_03",
    userName: "Lee Wei Ming",
    timestamp: "2026-06-03T14:06:55Z",
    meta: "OCR confidence: 94%",
  },
  {
    id: "evt_06",
    type: "processing_complete",
    documentId: "doc_002",
    documentName: "Vendor Agreement - Logistik Jaya.pdf",
    userId: "user_02",
    userName: "Siti Nurhaliza",
    timestamp: "2026-06-03T11:34:10Z",
    meta: "Text layer detected, OCR skipped",
  },
  {
    id: "evt_07",
    type: "download",
    documentId: "doc_001",
    documentName: "Invoice TNB May 2026.pdf",
    userId: "user_01",
    userName: "Ahmad Razif",
    timestamp: "2026-06-03T10:00:00Z",
  },
  {
    id: "evt_08",
    type: "processing_failed",
    documentId: "doc_008",
    documentName: "LHDN Tax Assessment Notice.pdf",
    userId: "user_01",
    userName: "Ahmad Razif",
    timestamp: "2026-06-02T16:31:00Z",
    meta: "Encrypted PDF — cannot extract text",
  },
];

export const storagePercent =
  Math.round(
    (mockTenant.storageUsedBytes / mockTenant.storageLimitBytes) * 100
  );

export function formatBytes(bytes: number): string {
  if (bytes >= 1_073_741_824) return `${(bytes / 1_073_741_824).toFixed(1)} GB`;
  if (bytes >= 1_048_576) return `${(bytes / 1_048_576).toFixed(1)} MB`;
  if (bytes >= 1_024) return `${(bytes / 1_024).toFixed(0)} KB`;
  return `${bytes} B`;
}

export function formatRelativeTime(isoString: string): string {
  const now = new Date("2026-06-04T09:15:00Z");
  const then = new Date(isoString);
  const diffMs = now.getTime() - then.getTime();
  const diffMins = Math.floor(diffMs / 60_000);
  if (diffMins < 1) return "just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
}
